export const CHANGE_BACKGROUND = "CHANGE_BACKGROUND";
export const CHANGE_HAT = "CHANGE_HAT";
export const CHANGE_ACCESSORY = "CHANGE_ACCESSORY";
export const UPDATE_AVATAR = "UPDATE_AVATAR";

export const PURCHASE_BACKGROUND = "PURCHASE_BACKGROUND";
export const PURCHASE_HAT = "PURCHASE_HAT";
export const PURCHASE_ACCESSORY = "PURCHASE_ACCESSORY";
export const PURCHASE_VOUCHER = "PURCHASE_VOUCHER";

export const INITIALISE_STATE = "INITIALISE_STATE";
